# Generated by Django 4.2.1 on 2023-05-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
