# Generated by Django 4.2.1 on 2023-05-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
